# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [1]:
# Import pandas using the standard alias
import pandas as pd

In [7]:
# Import the file and print the first 5 rows
df = pd.read_csv("Data/Zipcode_Demos.csv",skiprows=47)
df.head()

,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,48,10001,44,22,0.50,22,0.50,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
1,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
2,50,10003,1,1,1.00,0,0.00,0,0,1,...,1,100,0,0.00,1,1.00,0,0,1,100
3,51,10004,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,52,10005,2,2,1.00,0,0.00,0,0,2,...,2,100,0,0.00,2,1.00,0,0,2,100

In [9]:
# Print the last 5 rows of df
df.tail()

,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
5,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0.0,6,1.0,0,0,6,100
6,54,10007,1,0,0.00,1,1.00,0,0,1,...,1,100,1,1.0,0,0.0,0,0,1,100
7,55,10009,2,0,0.00,2,1.00,0,0,2,...,2,100,0,0.0,2,1.0,0,0,2,100
8,56,10010,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0,0
9,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0.0,3,1.0,0,0,3,100

In [ ]:
# What is going on with this data set? Anything unusual?

In [11]:
# Clean up the dataset
df.duplicated().any()

False

In [15]:
df.isnull().any()

47                                     False
JURISDICTION NAME                      False
COUNT PARTICIPANTS                     False
COUNT FEMALE                           False
PERCENT FEMALE                         False
COUNT MALE                             False
PERCENT MALE                           False
COUNT GENDER UNKNOWN                   False
PERCENT GENDER UNKNOWN                 False
COUNT GENDER TOTAL                     False
PERCENT GENDER TOTAL                   False
COUNT PACIFIC ISLANDER                 False
PERCENT PACIFIC ISLANDER               False
COUNT HISPANIC LATINO                  False
PERCENT HISPANIC LATINO                False
COUNT AMERICAN INDIAN                  False
PERCENT AMERICAN INDIAN                False
COUNT ASIAN NON HISPANIC               False
PERCENT ASIAN NON HISPANIC             False
COUNT WHITE NON HISPANIC               False
PERCENT WHITE NON HISPANIC             False
COUNT BLACK NON HISPANIC               False
PERCENT BLACK NON HISPANIC             False
COUNT OTHER ETHNICITY                  False
PERCENT OTHER ETHNICITY                False
COUNT ETHNICITY UNKNOWN                False
PERCENT ETHNICITY UNKNOWN              False
COUNT ETHNICITY TOTAL                  False
PERCENT ETHNICITY TOTAL                False
COUNT PERMANENT RESIDENT ALIEN         False
PERCENT PERMANENT RESIDENT ALIEN       False
COUNT US CITIZEN                       False
PERCENT US CITIZEN                     False
COUNT OTHER CITIZEN STATUS             False
PERCENT OTHER CITIZEN STATUS           False
COUNT CITIZEN STATUS UNKNOWN           False
PERCENT CITIZEN STATUS UNKNOWN         False
COUNT CITIZEN STATUS TOTAL             False
PERCENT CITIZEN STATUS TOTAL           False
COUNT RECEIVES PUBLIC ASSISTANCE       False
PERCENT RECEIVES PUBLIC ASSISTANCE     False
COUNT NRECEIVES PUBLIC ASSISTANCE      False
PERCENT NRECEIVES PUBLIC ASSISTANCE    False
COUNT PUBLIC ASSISTANCE UNKNOWN        False
PERCENT PUBLIC ASSISTANCE UNKNOWN      False
COUNT PUBLIC ASSISTANCE TOTAL          False
PERCENT PUBLIC ASSISTANCE TOTAL        False
dtype: bool

In [29]:
df.columns

Index(['JURISDICTION NAME', 'COUNT PARTICIPANTS', 'COUNT FEMALE',
       'PERCENT FEMALE', 'COUNT MALE', 'PERCENT MALE', 'COUNT GENDER UNKNOWN',
       'PERCENT GENDER UNKNOWN', 'COUNT GENDER TOTAL', 'PERCENT GENDER TOTAL',
       'COUNT PACIFIC ISLANDER', 'PERCENT PACIFIC ISLANDER',
       'COUNT HISPANIC LATINO', 'PERCENT HISPANIC LATINO',
       'COUNT AMERICAN INDIAN', 'PERCENT AMERICAN INDIAN',
       'COUNT ASIAN NON HISPANIC', 'PERCENT ASIAN NON HISPANIC',
       'COUNT WHITE NON HISPANIC', 'PERCENT WHITE NON HISPANIC',
       'COUNT BLACK NON HISPANIC', 'PERCENT BLACK NON HISPANIC',
       'COUNT OTHER ETHNICITY', 'PERCENT OTHER ETHNICITY',
       'COUNT ETHNICITY UNKNOWN', 'PERCENT ETHNICITY UNKNOWN',
       'COUNT ETHNICITY TOTAL', 'PERCENT ETHNICITY TOTAL',
       'COUNT PERMANENT RESIDENT ALIEN', 'PERCENT PERMANENT RESIDENT ALIEN',
       'COUNT US CITIZEN', 'PERCENT US CITIZEN', 'COUNT OTHER CITIZEN STATUS',
       'PERCENT OTHER CITIZEN STATUS', 'COUNT CITIZEN STATUS UNKNOWN',
       'PERCENT CITIZEN STATUS UNKNOWN', 'COUNT CITIZEN STATUS TOTAL',
       'PERCENT CITIZEN STATUS TOTAL', 'COUNT RECEIVES PUBLIC ASSISTANCE',
       'PERCENT RECEIVES PUBLIC ASSISTANCE',
       'COUNT NRECEIVES PUBLIC ASSISTANCE',
       'PERCENT NRECEIVES PUBLIC ASSISTANCE',
       'COUNT PUBLIC ASSISTANCE UNKNOWN', 'PERCENT PUBLIC ASSISTANCE UNKNOWN',
       'COUNT PUBLIC ASSISTANCE TOTAL', 'PERCENT PUBLIC ASSISTANCE TOTAL'],
      dtype='object')

In [ ]:
df= df.drop('47', axis=1)

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [33]:
# Hint: Here's a useful programming pattern to use
try:
    df = pd.read_csv('Yelp_Reviews_Corrupt.csv')
    df.head()

    # Do something
except Exception as e:
    print("Yelp file is missing")
    # Handle your exception e

Yelp file is missing

## Summary

Congratulations, you now practiced your Pandas-importing skills.